{% set name = "pyminizip" %}
{% set version = "0.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyminizip-{{ version }}.tar.gz
  sha256: 0a954dd2a65fd72c8b827b83fb806fb4f301075a6ec43e207d3345ab15843a7a

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyminizip
  commands:
    - pip check   # [unix and (python_impl != 'pypy')]
  requires:
    - pip

about:
  home: https://github.com/smihica/pyminizip
  summary: A minizip wrapper - To create a password encrypted zip file in python.
  license_file: COPYING.txt
  license: Zlib

extra:
  recipe-maintainers:
    - thewchan
